### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Ingvar-Y** [DissectMalware/pyxlsb2#5]
Hi!

I was wondering whether this project could be used with [pandas](https://github.com/pandas-dev/pandas) instead of original pyxlsb. However, they are rather strict with licensing questions.

The original pyxlsb was released under LGPLv3 (which was fine). It seems derived work can't be licensed under Apache 2.0 according to [this](http://www.apache.org/legal/resolved.html#category-x). You could consider relicensing pyxlsb2 under LGPLv3 so it would be compliant with licenses and usable.

**Comment by DissectMalware** [comment]
Hi Ingvar,

I think it does not apply to pyxlsb2 as at the time of forking the license was different:

https://github.com/DissectMalware/pyxlsb2/blob/master/LICENSE_pyxlsb

The above one was the license at the moment I forked from pyxlsb. They made a license change.

What do you think?

**Comment by DissectMalware** [comment]
Oh, it seems that I miss-read your request. You mean changing the license from Apache 2.0 to LGPLv3 so it can be used in Pandas?

**Comment by Ingvar-Y** [comment]
Oh, I see, pyxlsb master is licensed under MIT but release versions are licensed under LGPLv3 - that's weird. No, Apache 2.0 license is perfect and better suited for inclusion in non-GPL project like pandas. I am sorry for having bothered you.
